### ISSUE TITLE
照片时效性的问题

### ISSUE THREAD

**Issue by joybee007** [oxoooo/mantou_earth#14]
这些照片是实时拍摄的还是事先拍好的只是按时辰定时更换而已啊？日本右边和澳洲右边的两个气旋我观察很久了怎么还在那边啊。大陆和南海永远被浓雾笼罩啊~~

**Comment by xingrz** [comment]
卫星每 10 分钟拍摄一张照片，从卫星一路到我们服务器的传输和处理会有 40 分钟延迟。另外如果某次抓取的时候网络故障（可能是你的原因，也可能是我们的原因）也会跳过。

**Comment by joybee007** [comment]
哦，可能气旋移动得没我想象的快吧。
