### ISSUE TITLE
mac版思路

### ISSUE THREAD

**Issue by 1a57danc3** [oxoooo/mantou_earth#16]
其實只要利用api把himawari8.nict.go.jp的圖片down到本地文件夾，設置crontab定時任務重複下載行為，過期後把舊圖片刪除。

然後利用mac的壁紙設置自動輪播圖片，選擇剛剛的下載文件夾即可完成。

**Comment by 1a57danc3** [comment]
搜了一下  好像已经有了 https://gist.github.com/miao1007/54a2bdb012c643e9f826

**Comment by xingrz** [comment]
我们有自己的 CDN，以免将流量直接压到 NICT 上。因此下载部分的代码不开源。

**Comment by 1a57danc3** [comment]
不开源的二进制文件不能扔下载站吗？为什么要放Github上？

**Comment by xingrz** [comment]
一个项目，开源哪些模块，是由我——项目的所有人——决定的 :)
