### ISSUE TITLE
An application of Open-source Main Code

### ISSUE THREAD

**Issue by bitpeach** [oxoooo/mantou_earth#17]
Hi~ Nice to see you and your code.
Your Mantou_earth for Mac is an impressive achievement. 
However, I found your main code was unreadable.
Could you provide or make your "main" script publicly?
Thank you for reading this message and hope your approve.

**Comment by bitpeach** [comment]
I am so sory. I just read other closed issues. And I have understood why your team decided that, Thank you. Good luck!

**Comment by bitpeach** [comment]
However, it doesn't make sense.
The codes which are involved by your own CDN account or accelerating download can be hided. We can do the supplymentary work as bitdust shown in this [link](https://github.com/bitdust/EarthLiveSharp/issues/13), such as that we will complete our own CDN account to replace your account.
So you can publish your other codes and conceal the codes of CDN account.
If this can be permitted, could you update your code with your main code publicly?
Thank you for your beautiful work and we hope this issue can be approved by dear you.

**Comment by xingrz** [comment]
Hi @bitpeach 

The binary `main` is just a simple HTTP client written in Golang to download the image and print its name. What do the magic is [`run`](https://github.com/oxoooo/mantou_earth/blob/master/run). So nothing valuable to be open-source.

CC @mjason

**Comment by bitpeach** [comment]
@xingrz Thank you for your reply. We admire your work. Good luck.
