### ISSUE TITLE
最近地球没有更新了

### ISSUE THREAD

**Issue by clayzhu** [oxoooo/mantou_earth#18]
Hello，您好，这几天地球图片都没有更新了呢。谢谢。

**Comment by xingrz** [comment]
请更新到1.6.0

clayzhu notifications@github.com于2016年8月17日周三 09:51写道：

**Comment by clayzhu** [comment]
请问1.6.0这个版本号哪里查看的？是把原来的地球卸载，然后重装么？我在新的 iMac 上安装后，也没有反应。

**Comment by Rayleign** [comment]
mac版本的怎么升级

**Comment by clayzhu** [comment]
Hello，这个项目还有人维护吗？很喜欢这个馒头地球呢，希望还能继续呀。

**Comment by mjason** [comment]
我还在维护，不过最近忙着融资，也刚刚和又拍合作切换了数据源，我找个时间更新一下吧
