### ISSUE TITLE
按照说明做也没有更换成功

### ISSUE THREAD

**Issue by laoyang945** [oxoooo/mantou_earth#2]
需要做什么特别的设置吗？
另外，作者到处的错别字也太多了

**Comment by mjason** [comment]
不需要的，可以看看里面的日志cat .mantou_earth/err.log, 把里面的日志发给我一下

**Comment by jannerchang** [comment]
运行 install 后完全无反应啊，桌面还是我以前的桌面呢

**Comment by xingrz** [comment]
@jannerchang 跟着我再念一边 install 最后出来的那行字。
