### ISSUE TITLE
下载地址失效？

### ISSUE THREAD

**Issue by 1c7** [oxoooo/mantou_earth#20]
## 1 
用的是七牛吗？地址看起来像七牛的。
反正无法访问了。

## 2
http://www.appinn.com/mantou-earth-for-mac/
从其他地址下载到了。然后安装之后依然还是无法使用。
我的环境如下：
<img width="586" alt="3" src="https://cloud.githubusercontent.com/assets/1804755/21151824/e5bd55b4-c19e-11e6-84ef-495abfb7e37b.png">

## 3
不了解 mac 上的开发，只是想问下为啥不写个 .app 之类的方便用？
谢谢。(安卓版的很好用，非常感谢）

**Comment by xingrz** [comment]
mac版已经停止维护了很长时间了

**Comment by 1c7** [comment]
@xingrz  ok, 谢谢
