### ISSUE TITLE
MACbook pro的双屏幕下，只有主屏幕的壁纸被改了，能同时修改两个屏幕的壁纸吗？

### ISSUE THREAD

**Issue by zhurizhe** [oxoooo/mantou_earth#4]
或者告诉我配置的方法？

**Comment by isnofate** [comment]
同问，试过了，外接显示器还是之前的壁纸

**Comment by zcsunt** [comment]
外接显示器可以改的。只需要用鼠标在设置面板里把地球桌面拖过去。如图：
![qq20160107-0](https://cloud.githubusercontent.com/assets/2011989/12163837/c8222c92-b54b-11e5-9f08-924839480619.png)

**Comment by isnofate** [comment]
OK了，感谢

**Comment by ttthing111** [comment]
在每个屏幕独自设置一下
