### ISSUE TITLE
Make `main` open source

### ISSUE THREAD

**Issue by yzyzsun** [oxoooo/mantou_earth#5]
Since `main` is just a binary file without source code, I think it a little unsafe. Would you like to make it open source and let us compile it by ourselves?

**Comment by xingrz** [comment]
不能。

我们用了 CDN 来保存地球图片并加速下载，`main` 包含了这部分的源码，开放它会给我们带来额外的流量费用。

**Comment by yzyzsun** [comment]
@xingrz Got it.
