### ISSUE TITLE
invalid multibyte char (US-ASCII)

### ISSUE THREAD

**Issue by inferjay** [oxoooo/mantou_earth#6]
Error Message

> /Users/XXXX/Downloads/mac_mantou_earch/install:9: invalid multibyte char (US-ASCII)

OS Version: 10.11.2 (15C50)

System Language: English

**Comment by mjason** [comment]
ruby版本的问题，下午修复一下

**Comment by inferjay** [comment]
忘说了，我这里 Ruby 版本是 `ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin14.0.0]`

**Comment by mjason** [comment]
已经修复

**Comment by inferjay** [comment]
:+1: 去学习一下
